export { default as Background } from "./Background";
export { default as Header } from "./Header";
export { default as Divider } from "./Divider";
export { default as About } from "./About";
export { default as Connect } from "./Connect";
export { default as Experience } from "./Experience";
export { default as Projects } from "./Projects";
export { default as Skills } from "./Skills";
export { default as Footer } from "./Footer";
